### PR TITLE
contracts prefix fixes

### PR DESCRIPTION
**Pull request by forefy**
Hey guys,

While experimenting with wrapping aderyn, I discovered that I can't compile single files that has certain `@openzeppelin` styled imports

For example, an import like
`@openzeppelin/contracts/token...`

would be resolved as
`lib/openzeppelin-contracts/token..`

e.g. - the `contracts` directory will be removed unnecessarily.

In my local setup the commit in this PR helped, but I tested it mostly in my specific environment, so not sure how it affects use cases outside of that.

### CODE REVIEW

**Comment by alexroan** [comment]
Do you have an example repo and aderyn command that I can use to try to recreate this issue @tomer-aw ?

**Comment by forefy** [comment]
Sure, try `aderyn --src src/AAMintPass.sol` from the repo root of https://github.com/code-423n4/2024-02-ai-arena

Same issue also occurred for files at https://github.com/HashLips/hashlips_nft_contract

**Comment by alexroan** [comment]
Ahhh, OK, I can see where you may be having an issue. I'm using https://github.com/code-423n4/2024-02-ai-arena as in this example.

* Firstly, to make sure that remappings and dependencies are correctly setup, run `forge install` (because it's a forge repo)
* To run over the whole codebase, you can then run `aderyn` (this should work)
* To specifically include only a specific contract, use `-i`, like this: `aderyn -i AAMintPass.sol` <- This should achieve what you want to achieve.

Let me know how you get on with this @tomer-aw !

Some more context:

`--src` represents the location of the `src` folder. I.e., where the target contracts are kept in a Foundry or Hardhat repo, this is to avoid analyzing `lib`, `test`, and `script` contracts. 
It is auto-captured by `foundry.toml` in the Foundry case, so you don't need to use it. In Hardhat's case, you need it because aderyn can't currently read Hardhat config files. 

This feels like a devex issue, so if you have any better naming suggestions for these arguments, please let me know. I want to make this as intuitive as possible.

**Comment by forefy** [comment]
Yeah well, in that case as far as it goes for this specific use case I'm guessing just better documentation could probably replace having to merge this change, thanks!

**Pull request closed without merging**
